name: MentionedMessage
main: XanderID\MentionedMessage\MentionedMessage
description: now you can save MentionedMessage in UI
api: 4.0.0
version: 1.0.1
author: XanderID

permissions:
  mentionedmessage.use:
    description: "Permission to use MyMessage Commands"
    default: true
